language: node_js
node_js:
  - "18"

services: docker

# Pre-testing installs
install:
  - echo "nothing needs to be installed"

# Scripts to be run such as tests
before_script:
  - echo "no tests"
script:
  - docker build -t udagram-reverseproxy ./udagram-reverseproxy
  - docker build -t udagram-api-feed ./udagram-api-feed
  - docker build -t udagram-api-user ./udagram-api-user
  - docker build -t udagram-frontend ./udagram-frontend

  - docker tag udagram-reverseproxy mariamhindawi/udagram-reverseproxy
  - docker tag udagram-api-feed mariamhindawi/udagram-api-feed
  - docker tag udagram-api-user mariamhindawi/udagram-api-user
  - docker tag udagram-frontend mariamhindawi/udagram-frontend

  after success:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push mariamhindawi/udagram-reverseproxy
  - docker push mariamhindawi/udagram-api-feed
  - docker push mariamhindawi/udagram-api-user
  - docker push mariamhindawi/udagram-frontend